console.log('Hello, this is your starter pack, do whatever with it')
console.log('You can use react, vue, es6, pug, sass, and much more')
console.log('without needing to touch the configuration file')
console.log('')
console.log('It is the most welcoming environment to learning new')
console.log('things after coming from a vanilla context, I mean if')
console.log('you only used HTML, JS and CSS on your projects, this')
console.log('is where you can experiment with new stuff in a way you')
console.log('feel comfortable :D')
